### ISSUE TITLE
Uncaught exception 2: Color

### ISSUE THREAD

**Issue by Unrealf1** [mipt-npm/genphys-diffraction#5]
Если нарисовать достаточно короткую незамкнутую линию (да, такие не просят рисовать в руководстве, но непойманное исключение, после которого приложение виснет насмерть - не ожидаемое поведение) Воспроизводится легко - 5/5 раз получилось. Но если нарисовать линию > нескольких сантиметров - кнопки работают, и есть какой-то результат.
Проблема в том, что цвета либо > значения rgb либо > 255, либо < 0 (причём все сразу)

https://github.com/mipt-npm/genphys-diffraction/blob/1de0f40e97bf30e4b468bff2ebb777d4a995d6f8/src/jvmMain/kotlin/ru/mipt/phys/diffraction/AppFrame.kt#L129

![issue2-2](https://user-images.githubusercontent.com/36414426/61593860-d1627400-abed-11e9-9720-d1020e3484b4.png)
![issue-2-color_exeption](https://user-images.githubusercontent.com/36414426/61593861-d1627400-abed-11e9-9090-e2df211557c0.png)

Вывод:

> Exception in thread "DefaultDispatcher-worker-1" java.lang.IllegalArgumentException: Color parameter outside of expected range: Red Green Blue
	at java.desktop/java.awt.Color.testColorValueRange(Color.java:310)
	at java.desktop/java.awt.Color.<init>(Color.java:395)
	at java.desktop/java.awt.Color.<init>(Color.java:369)
	at ru.mipt.phys.diffraction.AppFrame$drawDiffractionPic$2.invokeSuspend(AppFrame.kt:129)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by Unrealf1** [comment]
Update:
Проблема повторяется с произвольной замкнутой достаточно маленькой фигурой
![Screenshot from 2019-07-21 19-54-05](https://user-images.githubusercontent.com/36414426/61594194-821e4280-abf1-11e9-85bc-95599e7080b8.png)
